### ISSUE TITLE
No clear indication of Diesel version compatibility

### ISSUE THREAD

**Issue by blackghost1987** [terry90/diesel-enum-derive#1]
Hi! I had an issue with upgrading to 1.0, I got the following error, which was really unhelpful:
```
#[derive(DieselEnum)]
  |          ^^^^^^^^^^ no `PgValue` in `pg`
```

After some digging I realized that the 1.4 version of Diesel really doesn't have this PgValue type, so it must be from Diesel 2.0.

Crates.io or the Cargo.toml does not indicate the Diesel crate as a direct dependency of this crate, and I couldn't find any info about compatible versions in the Readme or in the docs.

Am I correct to assume that diesel-enum-derive 0.1.4 is working with Diesel 1.4, but 1.0 only works with Diesel 2.0? If so, I think this information should be present somewhere.

Also please consider using git tags or the Releases in the repo to specify which Cargo version corresponds to which version of the code!

Let me know if I can help with anything, like creating a pull request or something.

**Comment by terry90** [comment]
Hi !
> Am I correct to assume that diesel-enum-derive 0.1.4 is working with Diesel 1.4, but 1.0 only works with Diesel 2.0? If so, I think this information should be present somewhere.

Yes indeed, that's why I bumped the version to 1.0, to indicate the fact that it's not compatible with 0.1.4. 

> Let me know if I can help with anything, like creating a pull request or something.

Thank you ! If you feel like it I'll be glad to accept PRs
